import mongoose from 'mongoose';
import { Topic } from '../modules/topics/topics.model.js';
import { Problem } from '../modules/problems/problems.model.js';
import { logger } from '../utils/logger.js';
import { env } from '../config/env.js';

/**
 * Topic seed data: 10 core DSA topics.
 */
const topicsSeed = [
  {
    slug: 'arrays',
    title: 'Arrays',
    description: 'Master array manipulation, searching, sorting, and two-pointer techniques.',
    order: 1,
    icon: '📊',
  },
  {
    slug: 'strings',
    title: 'Strings',
    description: 'String matching, manipulation, and pattern recognition problems.',
    order: 2,
    icon: '🔤',
  },
  {
    slug: 'linked-lists',
    title: 'Linked Lists',
    description: 'Singly, doubly, and circular linked list operations and pointer techniques.',
    order: 3,
    icon: '🔗',
  },
  {
    slug: 'stacks-queues',
    title: 'Stacks & Queues',
    description: 'Stack and queue operations, monotonic stacks, and deque problems.',
    order: 4,
    icon: '📚',
  },
  {
    slug: 'trees',
    title: 'Trees',
    description: 'Binary trees, BSTs, tree traversals, and construction problems.',
    order: 5,
    icon: '🌳',
  },
  {
    slug: 'graphs',
    title: 'Graphs',
    description: 'BFS, DFS, shortest path, topological sort, and union-find problems.',
    order: 6,
    icon: '🕸️',
  },
  {
    slug: 'dynamic-programming',
    title: 'Dynamic Programming',
    description: 'Memoization, tabulation, and classic DP patterns for optimization problems.',
    order: 7,
    icon: '🧮',
  },
  {
    slug: 'binary-search',
    title: 'Binary Search',
    description: 'Binary search on sorted arrays, search space reduction, and boundary finding.',
    order: 8,
    icon: '🔍',
  },
  {
    slug: 'greedy',
    title: 'Greedy Algorithms',
    description: 'Greedy choice property problems including interval scheduling and optimization.',
    order: 9,
    icon: '💰',
  },
  {
    slug: 'backtracking',
    title: 'Backtracking',
    description: 'Recursive exploration with constraint satisfaction and pruning techniques.',
    order: 10,
    icon: '🔙',
  },
];

/**
 * Problem seed data organized by topic slug.
 * 150 top interview problems across 10 topics (15 each).
 * Article links: GFG preferred, TakeUForward as fallback.
 */
const problemsSeed: Record<
  string,
  Array<{
    slug: string;
    title: string;
    difficulty: 'easy' | 'medium' | 'hard';
    tags: string[];
    platform: 'leetcode';
    problemUrl: string;
    youtubeUrl: string;
    articleUrl: string;
    companies: string[];
    order: number;
  }>
> = {
  arrays: [
    {
      slug: 'two-sum',
      title: 'Two Sum',
      difficulty: 'easy',
      tags: ['array', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/two-sum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=two+sum+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/check-if-pair-with-given-sum-exists-in-array/',
      companies: ['Google', 'Amazon', 'Meta'],
      order: 1,
    },
    {
      slug: 'best-time-to-buy-and-sell-stock',
      title: 'Best Time to Buy and Sell Stock',
      difficulty: 'easy',
      tags: ['array', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=best+time+to+buy+and+sell+stock',
      articleUrl: 'https://www.geeksforgeeks.org/best-time-to-buy-and-sell-stock/',
      companies: ['Amazon', 'Goldman Sachs', 'Meta'],
      order: 2,
    },
    {
      slug: 'contains-duplicate',
      title: 'Contains Duplicate',
      difficulty: 'easy',
      tags: ['array', 'hash-table', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/contains-duplicate/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=contains+duplicate+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/check-if-array-contains-duplicates/',
      companies: ['Amazon', 'Apple', 'Adobe'],
      order: 3,
    },
    {
      slug: 'maximum-subarray',
      title: 'Maximum Subarray',
      difficulty: 'medium',
      tags: ['array', 'dynamic-programming', 'divide-and-conquer'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/maximum-subarray/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=maximum+subarray+kadane',
      articleUrl: 'https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 4,
    },
    {
      slug: 'product-of-array-except-self',
      title: 'Product of Array Except Self',
      difficulty: 'medium',
      tags: ['array', 'prefix-sum'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/product-of-array-except-self/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=product+of+array+except+self',
      articleUrl: 'https://www.geeksforgeeks.org/a-product-array-puzzle/',
      companies: ['Amazon', 'Apple', 'Meta'],
      order: 5,
    },
    {
      slug: 'container-with-most-water',
      title: 'Container With Most Water',
      difficulty: 'medium',
      tags: ['array', 'two-pointers', 'greedy'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/container-with-most-water/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=container+with+most+water',
      articleUrl: 'https://www.geeksforgeeks.org/container-with-most-water/',
      companies: ['Amazon', 'Google', 'Bloomberg'],
      order: 6,
    },
    {
      slug: '3sum',
      title: '3Sum',
      difficulty: 'medium',
      tags: ['array', 'two-pointers', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/3sum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=3sum+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/find-a-triplet-that-sum-to-a-given-value/',
      companies: ['Meta', 'Amazon', 'Apple'],
      order: 7,
    },
    {
      slug: 'merge-intervals',
      title: 'Merge Intervals',
      difficulty: 'medium',
      tags: ['array', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/merge-intervals/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=merge+intervals+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/merging-intervals/',
      companies: ['Google', 'Meta', 'Bloomberg'],
      order: 8,
    },
    {
      slug: 'sort-colors',
      title: 'Sort Colors',
      difficulty: 'medium',
      tags: ['array', 'two-pointers', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/sort-colors/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=sort+colors+dutch+national+flag',
      articleUrl: 'https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 9,
    },
    {
      slug: 'next-permutation',
      title: 'Next Permutation',
      difficulty: 'medium',
      tags: ['array', 'two-pointers'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/next-permutation/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=next+permutation+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/next-permutation/',
      companies: ['Google', 'Amazon', 'Meta'],
      order: 10,
    },
    {
      slug: 'set-matrix-zeroes',
      title: 'Set Matrix Zeroes',
      difficulty: 'medium',
      tags: ['array', 'matrix', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/set-matrix-zeroes/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=set+matrix+zeroes',
      articleUrl: 'https://www.geeksforgeeks.org/a-boolean-matrix-question/',
      companies: ['Amazon', 'Microsoft', 'Meta'],
      order: 11,
    },
    {
      slug: 'spiral-matrix',
      title: 'Spiral Matrix',
      difficulty: 'medium',
      tags: ['array', 'matrix', 'simulation'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/spiral-matrix/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=spiral+matrix+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/print-a-given-matrix-in-spiral-form/',
      companies: ['Amazon', 'Apple', 'Microsoft'],
      order: 12,
    },
    {
      slug: 'trapping-rain-water',
      title: 'Trapping Rain Water',
      difficulty: 'hard',
      tags: ['array', 'two-pointers', 'stack', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/trapping-rain-water/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=trapping+rain+water',
      articleUrl: 'https://www.geeksforgeeks.org/trapping-rain-water/',
      companies: ['Google', 'Amazon', 'Goldman Sachs'],
      order: 13,
    },
    {
      slug: 'first-missing-positive',
      title: 'First Missing Positive',
      difficulty: 'hard',
      tags: ['array', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/first-missing-positive/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=first+missing+positive',
      articleUrl:
        'https://www.geeksforgeeks.org/find-the-smallest-positive-number-missing-from-an-unsorted-array/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 14,
    },
    {
      slug: 'sliding-window-maximum',
      title: 'Sliding Window Maximum',
      difficulty: 'hard',
      tags: ['array', 'sliding-window', 'deque', 'heap'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/sliding-window-maximum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=sliding+window+maximum',
      articleUrl:
        'https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 15,
    },
  ],

  strings: [
    {
      slug: 'valid-anagram',
      title: 'Valid Anagram',
      difficulty: 'easy',
      tags: ['string', 'hash-table', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/valid-anagram/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=valid+anagram+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/check-whether-two-strings-are-anagram-of-each-other/',
      companies: ['Amazon', 'Microsoft'],
      order: 1,
    },
    {
      slug: 'valid-palindrome',
      title: 'Valid Palindrome',
      difficulty: 'easy',
      tags: ['string', 'two-pointers'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/valid-palindrome/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=valid+palindrome+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/check-if-a-string-is-palindrome/',
      companies: ['Meta', 'Amazon', 'Microsoft'],
      order: 2,
    },
    {
      slug: 'longest-common-prefix',
      title: 'Longest Common Prefix',
      difficulty: 'easy',
      tags: ['string', 'trie'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/longest-common-prefix/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=longest+common+prefix+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/longest-common-prefix-using-sorting/',
      companies: ['Amazon', 'Google', 'Apple'],
      order: 3,
    },
    {
      slug: 'longest-substring-without-repeating-characters',
      title: 'Longest Substring Without Repeating Characters',
      difficulty: 'medium',
      tags: ['string', 'sliding-window', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
      youtubeUrl:
        'https://www.youtube.com/results?search_query=longest+substring+without+repeating',
      articleUrl:
        'https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 4,
    },
    {
      slug: 'longest-palindromic-substring',
      title: 'Longest Palindromic Substring',
      difficulty: 'medium',
      tags: ['string', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/longest-palindromic-substring/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=longest+palindromic+substring',
      articleUrl: 'https://www.geeksforgeeks.org/longest-palindromic-substring/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 5,
    },
    {
      slug: 'group-anagrams',
      title: 'Group Anagrams',
      difficulty: 'medium',
      tags: ['string', 'hash-table', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/group-anagrams/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=group+anagrams',
      articleUrl:
        'https://www.geeksforgeeks.org/given-a-sequence-of-words-print-all-anagrams-together/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 6,
    },
    {
      slug: 'string-to-integer-atoi',
      title: 'String to Integer (atoi)',
      difficulty: 'medium',
      tags: ['string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/string-to-integer-atoi/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=string+to+integer+atoi',
      articleUrl: 'https://www.geeksforgeeks.org/write-your-own-atoi/',
      companies: ['Amazon', 'Microsoft', 'Bloomberg'],
      order: 7,
    },
    {
      slug: 'longest-repeating-character-replacement',
      title: 'Longest Repeating Character Replacement',
      difficulty: 'medium',
      tags: ['string', 'sliding-window', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
      youtubeUrl:
        'https://www.youtube.com/results?search_query=longest+repeating+character+replacement',
      articleUrl: 'https://www.geeksforgeeks.org/longest-repeating-character-replacement/',
      companies: ['Google', 'Amazon', 'Uber'],
      order: 8,
    },
    {
      slug: 'palindromic-substrings',
      title: 'Palindromic Substrings',
      difficulty: 'medium',
      tags: ['string', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/palindromic-substrings/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=palindromic+substrings+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/count-palindrome-sub-strings-string/',
      companies: ['Meta', 'Amazon', 'Google'],
      order: 9,
    },
    {
      slug: 'encode-and-decode-strings',
      title: 'Encode and Decode Strings',
      difficulty: 'medium',
      tags: ['string', 'design'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/encode-and-decode-strings/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=encode+and+decode+strings',
      articleUrl: 'https://www.geeksforgeeks.org/encode-and-decode-strings/',
      companies: ['Google', 'Meta', 'Microsoft'],
      order: 10,
    },
    {
      slug: 'implement-strstr',
      title: 'Find the Index of the First Occurrence in a String',
      difficulty: 'easy',
      tags: ['string', 'two-pointers'],
      platform: 'leetcode',
      problemUrl:
        'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=implement+strstr+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/implement-strstr-function/',
      companies: ['Amazon', 'Microsoft', 'Apple'],
      order: 11,
    },
    {
      slug: 'zigzag-conversion',
      title: 'Zigzag Conversion',
      difficulty: 'medium',
      tags: ['string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/zigzag-conversion/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=zigzag+conversion+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/print-concatenation-of-zig-zag-string-form-in-n-rows/',
      companies: ['Amazon', 'Google'],
      order: 12,
    },
    {
      slug: 'minimum-window-substring',
      title: 'Minimum Window Substring',
      difficulty: 'hard',
      tags: ['string', 'sliding-window', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/minimum-window-substring/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=minimum+window+substring',
      articleUrl:
        'https://www.geeksforgeeks.org/find-the-smallest-window-in-a-string-containing-all-characters-of-another-string/',
      companies: ['Meta', 'Google', 'Uber'],
      order: 13,
    },
    {
      slug: 'longest-valid-parentheses',
      title: 'Longest Valid Parentheses',
      difficulty: 'hard',
      tags: ['string', 'dynamic-programming', 'stack'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/longest-valid-parentheses/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=longest+valid+parentheses',
      articleUrl: 'https://www.geeksforgeeks.org/length-of-the-longest-valid-substring/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 14,
    },
    {
      slug: 'regular-expression-matching',
      title: 'Regular Expression Matching',
      difficulty: 'hard',
      tags: ['string', 'dynamic-programming', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/regular-expression-matching/',
      youtubeUrl:
        'https://www.youtube.com/results?search_query=regular+expression+matching+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/implementing-regular-expression-matching/',
      companies: ['Google', 'Meta', 'Amazon'],
      order: 15,
    },
  ],

  'linked-lists': [
    {
      slug: 'reverse-linked-list',
      title: 'Reverse Linked List',
      difficulty: 'easy',
      tags: ['linked-list', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/reverse-linked-list/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=reverse+linked+list',
      articleUrl: 'https://www.geeksforgeeks.org/reverse-a-linked-list/',
      companies: ['Amazon', 'Microsoft', 'Apple'],
      order: 1,
    },
    {
      slug: 'merge-two-sorted-lists',
      title: 'Merge Two Sorted Lists',
      difficulty: 'easy',
      tags: ['linked-list', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/merge-two-sorted-lists/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=merge+two+sorted+lists',
      articleUrl: 'https://www.geeksforgeeks.org/merge-two-sorted-linked-lists/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 2,
    },
    {
      slug: 'linked-list-cycle',
      title: 'Linked List Cycle',
      difficulty: 'easy',
      tags: ['linked-list', 'two-pointers'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/linked-list-cycle/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=linked+list+cycle',
      articleUrl: 'https://www.geeksforgeeks.org/detect-loop-in-a-linked-list/',
      companies: ['Amazon', 'Microsoft'],
      order: 3,
    },
    {
      slug: 'middle-of-the-linked-list',
      title: 'Middle of the Linked List',
      difficulty: 'easy',
      tags: ['linked-list', 'two-pointers'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/middle-of-the-linked-list/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=middle+of+linked+list',
      articleUrl:
        'https://www.geeksforgeeks.org/write-a-c-function-to-print-the-middle-of-the-linked-list/',
      companies: ['Amazon', 'Apple'],
      order: 4,
    },
    {
      slug: 'palindrome-linked-list',
      title: 'Palindrome Linked List',
      difficulty: 'easy',
      tags: ['linked-list', 'two-pointers', 'stack', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/palindrome-linked-list/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=palindrome+linked+list',
      articleUrl:
        'https://www.geeksforgeeks.org/function-to-check-if-a-singly-linked-list-is-palindrome/',
      companies: ['Amazon', 'Meta', 'Microsoft'],
      order: 5,
    },
    {
      slug: 'remove-nth-node-from-end-of-list',
      title: 'Remove Nth Node From End of List',
      difficulty: 'medium',
      tags: ['linked-list', 'two-pointers'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=remove+nth+node+from+end',
      articleUrl:
        'https://www.geeksforgeeks.org/delete-nth-node-from-the-end-of-the-given-linked-list/',
      companies: ['Meta', 'Amazon'],
      order: 6,
    },
    {
      slug: 'add-two-numbers',
      title: 'Add Two Numbers',
      difficulty: 'medium',
      tags: ['linked-list', 'math', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/add-two-numbers/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=add+two+numbers+linked+list',
      articleUrl: 'https://www.geeksforgeeks.org/add-two-numbers-represented-by-linked-lists/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 7,
    },
    {
      slug: 'linked-list-cycle-ii',
      title: 'Linked List Cycle II',
      difficulty: 'medium',
      tags: ['linked-list', 'two-pointers'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/linked-list-cycle-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=linked+list+cycle+ii',
      articleUrl: 'https://www.geeksforgeeks.org/find-first-node-of-loop-in-a-linked-list/',
      companies: ['Amazon', 'Microsoft', 'Bloomberg'],
      order: 8,
    },
    {
      slug: 'reorder-list',
      title: 'Reorder List',
      difficulty: 'medium',
      tags: ['linked-list', 'two-pointers', 'stack', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/reorder-list/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=reorder+list+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/rearrange-a-given-linked-list-in-place/',
      companies: ['Amazon', 'Meta', 'Bloomberg'],
      order: 9,
    },
    {
      slug: 'sort-list',
      title: 'Sort List',
      difficulty: 'medium',
      tags: ['linked-list', 'two-pointers', 'divide-and-conquer', 'sorting', 'merge-sort'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/sort-list/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=sort+list+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/merge-sort-for-linked-list/',
      companies: ['Meta', 'Google', 'Amazon'],
      order: 10,
    },
    {
      slug: 'copy-list-with-random-pointer',
      title: 'Copy List with Random Pointer',
      difficulty: 'medium',
      tags: ['linked-list', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=copy+list+with+random+pointer',
      articleUrl: 'https://www.geeksforgeeks.org/a-linked-list-with-next-and-arbit-pointer/',
      companies: ['Amazon', 'Meta', 'Microsoft'],
      order: 11,
    },
    {
      slug: 'intersection-of-two-linked-lists',
      title: 'Intersection of Two Linked Lists',
      difficulty: 'easy',
      tags: ['linked-list', 'two-pointers'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/intersection-of-two-linked-lists/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=intersection+of+two+linked+lists',
      articleUrl:
        'https://www.geeksforgeeks.org/write-a-function-to-get-the-intersection-point-of-two-linked-lists/',
      companies: ['Amazon', 'Microsoft', 'Bloomberg'],
      order: 12,
    },
    {
      slug: 'lru-cache',
      title: 'LRU Cache',
      difficulty: 'medium',
      tags: ['linked-list', 'hash-table', 'design'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/lru-cache/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=lru+cache+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/lru-cache-implementation/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 13,
    },
    {
      slug: 'merge-k-sorted-lists',
      title: 'Merge k Sorted Lists',
      difficulty: 'hard',
      tags: ['linked-list', 'divide-and-conquer', 'heap'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/merge-k-sorted-lists/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=merge+k+sorted+lists',
      articleUrl: 'https://www.geeksforgeeks.org/merge-k-sorted-linked-lists/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 14,
    },
    {
      slug: 'reverse-nodes-in-k-group',
      title: 'Reverse Nodes in k-Group',
      difficulty: 'hard',
      tags: ['linked-list', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=reverse+nodes+in+k+group',
      articleUrl: 'https://www.geeksforgeeks.org/reverse-a-linked-list-in-groups-of-given-size/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 15,
    },
  ],

  'stacks-queues': [
    {
      slug: 'valid-parentheses',
      title: 'Valid Parentheses',
      difficulty: 'easy',
      tags: ['stack', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/valid-parentheses/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=valid+parentheses',
      articleUrl: 'https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-an-expression/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 1,
    },
    {
      slug: 'implement-queue-using-stacks',
      title: 'Implement Queue using Stacks',
      difficulty: 'easy',
      tags: ['stack', 'queue', 'design'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/implement-queue-using-stacks/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=implement+queue+using+stacks',
      articleUrl: 'https://www.geeksforgeeks.org/queue-using-stacks/',
      companies: ['Amazon', 'Microsoft', 'Apple'],
      order: 2,
    },
    {
      slug: 'implement-stack-using-queues',
      title: 'Implement Stack using Queues',
      difficulty: 'easy',
      tags: ['stack', 'queue', 'design'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/implement-stack-using-queues/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=implement+stack+using+queues',
      articleUrl: 'https://www.geeksforgeeks.org/implement-stack-using-queue/',
      companies: ['Amazon', 'Google'],
      order: 3,
    },
    {
      slug: 'min-stack',
      title: 'Min Stack',
      difficulty: 'medium',
      tags: ['stack', 'design'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/min-stack/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=min+stack',
      articleUrl:
        'https://www.geeksforgeeks.org/design-a-stack-that-supports-getmin-in-o1-time-and-o1-extra-space/',
      companies: ['Amazon', 'Microsoft', 'Bloomberg'],
      order: 4,
    },
    {
      slug: 'next-greater-element-i',
      title: 'Next Greater Element I',
      difficulty: 'easy',
      tags: ['stack', 'array', 'hash-table', 'monotonic-stack'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/next-greater-element-i/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=next+greater+element+i',
      articleUrl: 'https://www.geeksforgeeks.org/next-greater-element/',
      companies: ['Amazon', 'Bloomberg'],
      order: 5,
    },
    {
      slug: 'daily-temperatures',
      title: 'Daily Temperatures',
      difficulty: 'medium',
      tags: ['stack', 'monotonic-stack'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/daily-temperatures/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=daily+temperatures',
      articleUrl: 'https://www.geeksforgeeks.org/number-of-days-until-warmer-temperature/',
      companies: ['Google', 'Amazon'],
      order: 6,
    },
    {
      slug: 'evaluate-reverse-polish-notation',
      title: 'Evaluate Reverse Polish Notation',
      difficulty: 'medium',
      tags: ['stack', 'math'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=evaluate+reverse+polish+notation',
      articleUrl: 'https://www.geeksforgeeks.org/evaluation-of-postfix-expression/',
      companies: ['Amazon', 'LinkedIn'],
      order: 7,
    },
    {
      slug: 'asteroid-collision',
      title: 'Asteroid Collision',
      difficulty: 'medium',
      tags: ['stack', 'array', 'simulation'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/asteroid-collision/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=asteroid+collision+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/asteroid-collision/',
      companies: ['Amazon', 'Google', 'Bloomberg'],
      order: 8,
    },
    {
      slug: 'decode-string',
      title: 'Decode String',
      difficulty: 'medium',
      tags: ['stack', 'string', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/decode-string/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=decode+string+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/decode-string-recursively-encoded-count-followed-substring/',
      companies: ['Google', 'Amazon', 'Bloomberg'],
      order: 9,
    },
    {
      slug: 'online-stock-span',
      title: 'Online Stock Span',
      difficulty: 'medium',
      tags: ['stack', 'monotonic-stack', 'design'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/online-stock-span/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=online+stock+span',
      articleUrl: 'https://www.geeksforgeeks.org/the-stock-span-problem/',
      companies: ['Amazon', 'Bloomberg'],
      order: 10,
    },
    {
      slug: 'car-fleet',
      title: 'Car Fleet',
      difficulty: 'medium',
      tags: ['stack', 'array', 'sorting', 'monotonic-stack'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/car-fleet/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=car+fleet+leetcode',
      articleUrl: '',
      companies: ['Google', 'Amazon'],
      order: 11,
    },
    {
      slug: 'simplify-path',
      title: 'Simplify Path',
      difficulty: 'medium',
      tags: ['stack', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/simplify-path/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=simplify+path+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/simplify-directory-path-unix-like/',
      companies: ['Meta', 'Amazon', 'Microsoft'],
      order: 12,
    },
    {
      slug: 'largest-rectangle-in-histogram',
      title: 'Largest Rectangle in Histogram',
      difficulty: 'hard',
      tags: ['stack', 'monotonic-stack'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=largest+rectangle+in+histogram',
      articleUrl: 'https://www.geeksforgeeks.org/largest-rectangle-under-histogram/',
      companies: ['Google', 'Amazon', 'Microsoft'],
      order: 13,
    },
    {
      slug: 'trapping-rain-water-stack',
      title: 'Trapping Rain Water',
      difficulty: 'hard',
      tags: ['stack', 'array', 'two-pointers', 'monotonic-stack'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/trapping-rain-water/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=trapping+rain+water+stack',
      articleUrl: 'https://www.geeksforgeeks.org/trapping-rain-water/',
      companies: ['Google', 'Amazon', 'Goldman Sachs'],
      order: 14,
    },
    {
      slug: 'basic-calculator',
      title: 'Basic Calculator',
      difficulty: 'hard',
      tags: ['stack', 'math', 'string', 'recursion'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/basic-calculator/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=basic+calculator+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/expression-evaluation/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 15,
    },
  ],

  trees: [
    {
      slug: 'maximum-depth-of-binary-tree',
      title: 'Maximum Depth of Binary Tree',
      difficulty: 'easy',
      tags: ['tree', 'dfs', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=maximum+depth+binary+tree',
      articleUrl: 'https://www.geeksforgeeks.org/find-the-maximum-depth-or-height-of-a-tree/',
      companies: ['Amazon', 'Google'],
      order: 1,
    },
    {
      slug: 'invert-binary-tree',
      title: 'Invert Binary Tree',
      difficulty: 'easy',
      tags: ['tree', 'dfs', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/invert-binary-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=invert+binary+tree',
      articleUrl:
        'https://www.geeksforgeeks.org/write-an-efficient-c-function-to-convert-a-tree-into-its-mirror-tree/',
      companies: ['Google', 'Amazon'],
      order: 2,
    },
    {
      slug: 'same-tree',
      title: 'Same Tree',
      difficulty: 'easy',
      tags: ['tree', 'dfs', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/same-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=same+tree+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/write-c-code-to-determine-if-two-trees-are-identical/',
      companies: ['Amazon', 'Microsoft'],
      order: 3,
    },
    {
      slug: 'subtree-of-another-tree',
      title: 'Subtree of Another Tree',
      difficulty: 'easy',
      tags: ['tree', 'dfs', 'string-matching', 'hash'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/subtree-of-another-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=subtree+of+another+tree',
      articleUrl:
        'https://www.geeksforgeeks.org/check-if-a-binary-tree-is-subtree-of-another-binary-tree/',
      companies: ['Amazon', 'Meta', 'Microsoft'],
      order: 4,
    },
    {
      slug: 'diameter-of-binary-tree',
      title: 'Diameter of Binary Tree',
      difficulty: 'easy',
      tags: ['tree', 'dfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/diameter-of-binary-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=diameter+of+binary+tree',
      articleUrl: 'https://www.geeksforgeeks.org/diameter-of-a-binary-tree/',
      companies: ['Meta', 'Google', 'Amazon'],
      order: 5,
    },
    {
      slug: 'balanced-binary-tree',
      title: 'Balanced Binary Tree',
      difficulty: 'easy',
      tags: ['tree', 'dfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/balanced-binary-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=balanced+binary+tree',
      articleUrl: 'https://www.geeksforgeeks.org/how-to-determine-if-a-binary-tree-is-balanced/',
      companies: ['Amazon', 'Google', 'Bloomberg'],
      order: 6,
    },
    {
      slug: 'binary-tree-level-order-traversal',
      title: 'Binary Tree Level Order Traversal',
      difficulty: 'medium',
      tags: ['tree', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=binary+tree+level+order+traversal',
      articleUrl: 'https://www.geeksforgeeks.org/level-order-tree-traversal/',
      companies: ['Amazon', 'Meta', 'Microsoft'],
      order: 7,
    },
    {
      slug: 'validate-binary-search-tree',
      title: 'Validate Binary Search Tree',
      difficulty: 'medium',
      tags: ['tree', 'dfs', 'bst'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/validate-binary-search-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=validate+binary+search+tree',
      articleUrl:
        'https://www.geeksforgeeks.org/a-program-to-check-if-a-binary-tree-is-bst-or-not/',
      companies: ['Amazon', 'Meta', 'Bloomberg'],
      order: 8,
    },
    {
      slug: 'kth-smallest-element-in-a-bst',
      title: 'Kth Smallest Element in a BST',
      difficulty: 'medium',
      tags: ['tree', 'dfs', 'bst'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=kth+smallest+element+bst',
      articleUrl:
        'https://www.geeksforgeeks.org/find-k-th-smallest-element-in-bst-order-statistics-in-bst/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 9,
    },
    {
      slug: 'lowest-common-ancestor-of-a-binary-search-tree',
      title: 'Lowest Common Ancestor of a Binary Search Tree',
      difficulty: 'medium',
      tags: ['tree', 'dfs', 'bst'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=lowest+common+ancestor+bst',
      articleUrl: 'https://www.geeksforgeeks.org/lowest-common-ancestor-in-a-binary-search-tree/',
      companies: ['Amazon', 'Meta', 'Microsoft'],
      order: 10,
    },
    {
      slug: 'lowest-common-ancestor-of-a-binary-tree',
      title: 'Lowest Common Ancestor of a Binary Tree',
      difficulty: 'medium',
      tags: ['tree', 'dfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=lowest+common+ancestor+binary+tree',
      articleUrl: 'https://www.geeksforgeeks.org/lowest-common-ancestor-binary-tree-set-1/',
      companies: ['Meta', 'Amazon', 'Microsoft'],
      order: 11,
    },
    {
      slug: 'construct-binary-tree-from-preorder-and-inorder-traversal',
      title: 'Construct Binary Tree from Preorder and Inorder Traversal',
      difficulty: 'medium',
      tags: ['tree', 'dfs', 'array', 'hash-table', 'divide-and-conquer'],
      platform: 'leetcode',
      problemUrl:
        'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
      youtubeUrl:
        'https://www.youtube.com/results?search_query=construct+binary+tree+preorder+inorder',
      articleUrl:
        'https://www.geeksforgeeks.org/construct-tree-from-given-inorder-and-preorder-traversal/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 12,
    },
    {
      slug: 'binary-tree-right-side-view',
      title: 'Binary Tree Right Side View',
      difficulty: 'medium',
      tags: ['tree', 'dfs', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/binary-tree-right-side-view/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=binary+tree+right+side+view',
      articleUrl: 'https://www.geeksforgeeks.org/print-right-view-binary-tree-2/',
      companies: ['Meta', 'Amazon', 'Bloomberg'],
      order: 13,
    },
    {
      slug: 'binary-tree-maximum-path-sum',
      title: 'Binary Tree Maximum Path Sum',
      difficulty: 'hard',
      tags: ['tree', 'dfs', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=binary+tree+maximum+path+sum',
      articleUrl: 'https://www.geeksforgeeks.org/find-maximum-path-sum-in-a-binary-tree/',
      companies: ['Google', 'Meta', 'Microsoft'],
      order: 14,
    },
    {
      slug: 'serialize-and-deserialize-binary-tree',
      title: 'Serialize and Deserialize Binary Tree',
      difficulty: 'hard',
      tags: ['tree', 'dfs', 'bfs', 'design', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=serialize+deserialize+binary+tree',
      articleUrl: 'https://www.geeksforgeeks.org/serialize-deserialize-binary-tree/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 15,
    },
  ],

  graphs: [
    {
      slug: 'number-of-islands',
      title: 'Number of Islands',
      difficulty: 'medium',
      tags: ['graph', 'dfs', 'bfs', 'union-find'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/number-of-islands/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=number+of+islands',
      articleUrl: 'https://www.geeksforgeeks.org/find-the-number-of-islands-using-dfs/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 1,
    },
    {
      slug: 'clone-graph',
      title: 'Clone Graph',
      difficulty: 'medium',
      tags: ['graph', 'dfs', 'bfs', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/clone-graph/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=clone+graph',
      articleUrl: 'https://www.geeksforgeeks.org/clone-an-undirected-graph/',
      companies: ['Meta', 'Google', 'Amazon'],
      order: 2,
    },
    {
      slug: 'course-schedule',
      title: 'Course Schedule',
      difficulty: 'medium',
      tags: ['graph', 'topological-sort', 'dfs', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/course-schedule/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=course+schedule',
      articleUrl: 'https://www.geeksforgeeks.org/detect-cycle-in-a-directed-graph-using-bfs/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 3,
    },
    {
      slug: 'course-schedule-ii',
      title: 'Course Schedule II',
      difficulty: 'medium',
      tags: ['graph', 'topological-sort', 'dfs', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/course-schedule-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=course+schedule+ii',
      articleUrl: 'https://www.geeksforgeeks.org/topological-sorting/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 4,
    },
    {
      slug: 'pacific-atlantic-water-flow',
      title: 'Pacific Atlantic Water Flow',
      difficulty: 'medium',
      tags: ['graph', 'dfs', 'bfs', 'matrix'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=pacific+atlantic+water+flow',
      articleUrl: 'https://www.geeksforgeeks.org/pacific-atlantic-water-flow/',
      companies: ['Google', 'Amazon'],
      order: 5,
    },
    {
      slug: 'rotting-oranges',
      title: 'Rotting Oranges',
      difficulty: 'medium',
      tags: ['graph', 'bfs', 'matrix'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/rotting-oranges/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=rotting+oranges',
      articleUrl:
        'https://www.geeksforgeeks.org/minimum-time-required-so-that-all-oranges-become-rotten/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 6,
    },
    {
      slug: 'surrounded-regions',
      title: 'Surrounded Regions',
      difficulty: 'medium',
      tags: ['graph', 'dfs', 'bfs', 'matrix', 'union-find'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/surrounded-regions/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=surrounded+regions',
      articleUrl: 'https://www.geeksforgeeks.org/given-matrix-o-x-replace-o-x-surrounded-x/',
      companies: ['Google', 'Amazon', 'Microsoft'],
      order: 7,
    },
    {
      slug: 'graph-valid-tree',
      title: 'Graph Valid Tree',
      difficulty: 'medium',
      tags: ['graph', 'dfs', 'bfs', 'union-find'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/graph-valid-tree/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=graph+valid+tree',
      articleUrl: 'https://www.geeksforgeeks.org/check-given-graph-tree/',
      companies: ['Google', 'Amazon', 'Meta'],
      order: 8,
    },
    {
      slug: 'number-of-connected-components-in-an-undirected-graph',
      title: 'Number of Connected Components in an Undirected Graph',
      difficulty: 'medium',
      tags: ['graph', 'dfs', 'bfs', 'union-find'],
      platform: 'leetcode',
      problemUrl:
        'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=number+connected+components+graph',
      articleUrl: 'https://www.geeksforgeeks.org/connected-components-in-an-undirected-graph/',
      companies: ['Google', 'Amazon', 'Meta'],
      order: 9,
    },
    {
      slug: 'redundant-connection',
      title: 'Redundant Connection',
      difficulty: 'medium',
      tags: ['graph', 'union-find', 'dfs', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/redundant-connection/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=redundant+connection+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/detect-cycle-undirected-graph/',
      companies: ['Google', 'Amazon'],
      order: 10,
    },
    {
      slug: 'cheapest-flights-within-k-stops',
      title: 'Cheapest Flights Within K Stops',
      difficulty: 'medium',
      tags: ['graph', 'dynamic-programming', 'bfs', 'shortest-path'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=cheapest+flights+within+k+stops',
      articleUrl: 'https://www.geeksforgeeks.org/cheapest-flights-within-k-stops/',
      companies: ['Amazon', 'Google', 'Bloomberg'],
      order: 11,
    },
    {
      slug: 'network-delay-time',
      title: 'Network Delay Time',
      difficulty: 'medium',
      tags: ['graph', 'shortest-path', 'heap'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/network-delay-time/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=network+delay+time',
      articleUrl: 'https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/',
      companies: ['Amazon', 'Google'],
      order: 12,
    },
    {
      slug: 'word-ladder',
      title: 'Word Ladder',
      difficulty: 'hard',
      tags: ['graph', 'bfs', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/word-ladder/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=word+ladder',
      articleUrl:
        'https://www.geeksforgeeks.org/word-ladder-length-of-shortest-chain-to-reach-a-target-word/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 13,
    },
    {
      slug: 'alien-dictionary',
      title: 'Alien Dictionary',
      difficulty: 'hard',
      tags: ['graph', 'topological-sort', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/alien-dictionary/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=alien+dictionary+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/given-sorted-dictionary-find-precedence-characters/',
      companies: ['Meta', 'Google', 'Amazon'],
      order: 14,
    },
    {
      slug: 'reconstruct-itinerary',
      title: 'Reconstruct Itinerary',
      difficulty: 'hard',
      tags: ['graph', 'dfs', 'eulerian-circuit'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/reconstruct-itinerary/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=reconstruct+itinerary',
      articleUrl: 'https://www.geeksforgeeks.org/reconstruct-itinerary-in-order/',
      companies: ['Google', 'Amazon', 'Uber'],
      order: 15,
    },
  ],

  'dynamic-programming': [
    {
      slug: 'climbing-stairs',
      title: 'Climbing Stairs',
      difficulty: 'easy',
      tags: ['dynamic-programming', 'math'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/climbing-stairs/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=climbing+stairs',
      articleUrl: 'https://www.geeksforgeeks.org/count-ways-reach-nth-stair/',
      companies: ['Amazon', 'Google', 'Apple'],
      order: 1,
    },
    {
      slug: 'min-cost-climbing-stairs',
      title: 'Min Cost Climbing Stairs',
      difficulty: 'easy',
      tags: ['dynamic-programming', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/min-cost-climbing-stairs/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=min+cost+climbing+stairs',
      articleUrl:
        'https://www.geeksforgeeks.org/minimum-cost-to-reach-the-top-of-the-floor-by-climbing-stairs/',
      companies: ['Amazon', 'Google'],
      order: 2,
    },
    {
      slug: 'house-robber',
      title: 'House Robber',
      difficulty: 'medium',
      tags: ['dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/house-robber/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=house+robber',
      articleUrl: 'https://www.geeksforgeeks.org/find-maximum-possible-stolen-value-houses/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 3,
    },
    {
      slug: 'house-robber-ii',
      title: 'House Robber II',
      difficulty: 'medium',
      tags: ['dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/house-robber-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=house+robber+ii',
      articleUrl:
        'https://www.geeksforgeeks.org/maximum-stolen-value-from-circular-arrangement-of-houses/',
      companies: ['Amazon', 'Google'],
      order: 4,
    },
    {
      slug: 'coin-change',
      title: 'Coin Change',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'bfs'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/coin-change/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=coin+change',
      articleUrl: 'https://www.geeksforgeeks.org/find-minimum-number-of-coins-that-make-a-change/',
      companies: ['Amazon', 'Google', 'Goldman Sachs'],
      order: 5,
    },
    {
      slug: 'longest-increasing-subsequence',
      title: 'Longest Increasing Subsequence',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'binary-search'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/longest-increasing-subsequence/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=longest+increasing+subsequence',
      articleUrl: 'https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 6,
    },
    {
      slug: 'longest-common-subsequence',
      title: 'Longest Common Subsequence',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/longest-common-subsequence/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=longest+common+subsequence',
      articleUrl: 'https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/',
      companies: ['Amazon', 'Google'],
      order: 7,
    },
    {
      slug: 'word-break',
      title: 'Word Break',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'hash-table', 'string', 'trie'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/word-break/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=word+break+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/word-break-problem-dp-32/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 8,
    },
    {
      slug: 'decode-ways',
      title: 'Decode Ways',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/decode-ways/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=decode+ways+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/count-possible-decodings-given-digit-sequence/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 9,
    },
    {
      slug: 'unique-paths',
      title: 'Unique Paths',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'math', 'combinatorics'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/unique-paths/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=unique+paths+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/count-possible-paths-top-left-bottom-right-nxm-matrix/',
      companies: ['Amazon', 'Google', 'Bloomberg'],
      order: 10,
    },
    {
      slug: 'partition-equal-subset-sum',
      title: 'Partition Equal Subset Sum',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/partition-equal-subset-sum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=partition+equal+subset+sum',
      articleUrl: 'https://www.geeksforgeeks.org/partition-problem-dp-18/',
      companies: ['Amazon', 'Meta'],
      order: 11,
    },
    {
      slug: 'target-sum',
      title: 'Target Sum',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'backtracking'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/target-sum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=target+sum+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/target-sum/',
      companies: ['Meta', 'Google', 'Amazon'],
      order: 12,
    },
    {
      slug: 'edit-distance',
      title: 'Edit Distance',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/edit-distance/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=edit+distance',
      articleUrl: 'https://www.geeksforgeeks.org/edit-distance-dp-5/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 13,
    },
    {
      slug: '0-1-knapsack',
      title: 'Ones and Zeroes',
      difficulty: 'medium',
      tags: ['dynamic-programming', 'array', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/ones-and-zeroes/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=ones+and+zeroes+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/',
      companies: ['Google', 'Amazon'],
      order: 14,
    },
    {
      slug: 'burst-balloons',
      title: 'Burst Balloons',
      difficulty: 'hard',
      tags: ['dynamic-programming', 'divide-and-conquer'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/burst-balloons/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=burst+balloons+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/burst-balloons-to-maximize-coins/',
      companies: ['Google', 'Amazon', 'Microsoft'],
      order: 15,
    },
  ],

  'binary-search': [
    {
      slug: 'binary-search',
      title: 'Binary Search',
      difficulty: 'easy',
      tags: ['binary-search', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/binary-search/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=binary+search+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/binary-search/',
      companies: ['Amazon', 'Microsoft'],
      order: 1,
    },
    {
      slug: 'search-insert-position',
      title: 'Search Insert Position',
      difficulty: 'easy',
      tags: ['binary-search', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/search-insert-position/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=search+insert+position',
      articleUrl: 'https://www.geeksforgeeks.org/search-insert-position-of-k-in-a-sorted-array/',
      companies: ['Amazon', 'Google'],
      order: 2,
    },
    {
      slug: 'find-first-and-last-position-of-element-in-sorted-array',
      title: 'Find First and Last Position of Element in Sorted Array',
      difficulty: 'medium',
      tags: ['binary-search', 'array'],
      platform: 'leetcode',
      problemUrl:
        'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',
      youtubeUrl:
        'https://www.youtube.com/results?search_query=first+and+last+position+sorted+array',
      articleUrl:
        'https://www.geeksforgeeks.org/find-first-and-last-positions-of-an-element-in-a-sorted-array/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 3,
    },
    {
      slug: 'search-in-rotated-sorted-array',
      title: 'Search in Rotated Sorted Array',
      difficulty: 'medium',
      tags: ['binary-search', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=search+in+rotated+sorted+array',
      articleUrl: 'https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/',
      companies: ['Amazon', 'Meta', 'Microsoft'],
      order: 4,
    },
    {
      slug: 'find-minimum-in-rotated-sorted-array',
      title: 'Find Minimum in Rotated Sorted Array',
      difficulty: 'medium',
      tags: ['binary-search', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
      youtubeUrl:
        'https://www.youtube.com/results?search_query=find+minimum+in+rotated+sorted+array',
      articleUrl:
        'https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/',
      companies: ['Amazon', 'Goldman Sachs', 'Google'],
      order: 5,
    },
    {
      slug: 'search-a-2d-matrix',
      title: 'Search a 2D Matrix',
      difficulty: 'medium',
      tags: ['binary-search', 'array', 'matrix'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/search-a-2d-matrix/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=search+a+2d+matrix',
      articleUrl: 'https://www.geeksforgeeks.org/search-in-row-wise-and-column-wise-sorted-matrix/',
      companies: ['Amazon', 'Microsoft', 'Bloomberg'],
      order: 6,
    },
    {
      slug: 'koko-eating-bananas',
      title: 'Koko Eating Bananas',
      difficulty: 'medium',
      tags: ['binary-search'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/koko-eating-bananas/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=koko+eating+bananas',
      articleUrl: 'https://www.geeksforgeeks.org/koko-eating-bananas/',
      companies: ['Google', 'Amazon'],
      order: 7,
    },
    {
      slug: 'find-peak-element',
      title: 'Find Peak Element',
      difficulty: 'medium',
      tags: ['binary-search', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/find-peak-element/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=find+peak+element',
      articleUrl: 'https://www.geeksforgeeks.org/find-a-peak-in-a-given-array/',
      companies: ['Meta', 'Google', 'Amazon'],
      order: 8,
    },
    {
      slug: 'capacity-to-ship-packages-within-d-days',
      title: 'Capacity To Ship Packages Within D Days',
      difficulty: 'medium',
      tags: ['binary-search', 'array', 'greedy'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=capacity+to+ship+packages',
      articleUrl:
        'https://www.geeksforgeeks.org/minimum-capacity-of-ship-to-ship-all-packages-within-given-days/',
      companies: ['Amazon', 'Google'],
      order: 9,
    },
    {
      slug: 'time-based-key-value-store',
      title: 'Time Based Key-Value Store',
      difficulty: 'medium',
      tags: ['binary-search', 'hash-table', 'design', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/time-based-key-value-store/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=time+based+key+value+store',
      articleUrl: '',
      companies: ['Google', 'Amazon', 'Lyft'],
      order: 10,
    },
    {
      slug: 'single-element-in-a-sorted-array',
      title: 'Single Element in a Sorted Array',
      difficulty: 'medium',
      tags: ['binary-search', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/single-element-in-a-sorted-array/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=single+element+sorted+array',
      articleUrl:
        'https://www.geeksforgeeks.org/find-the-element-that-appears-once-in-a-sorted-array/',
      companies: ['Amazon', 'Microsoft', 'Google'],
      order: 11,
    },
    {
      slug: 'split-array-largest-sum',
      title: 'Split Array Largest Sum',
      difficulty: 'hard',
      tags: ['binary-search', 'array', 'dynamic-programming', 'greedy'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/split-array-largest-sum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=split+array+largest+sum',
      articleUrl: 'https://www.geeksforgeeks.org/split-the-given-array-into-k-sub-arrays/',
      companies: ['Google', 'Amazon', 'Meta'],
      order: 12,
    },
    {
      slug: 'median-of-two-sorted-arrays',
      title: 'Median of Two Sorted Arrays',
      difficulty: 'hard',
      tags: ['binary-search', 'array', 'divide-and-conquer'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=median+of+two+sorted+arrays',
      articleUrl: 'https://www.geeksforgeeks.org/median-of-two-sorted-arrays-of-different-sizes/',
      companies: ['Amazon', 'Google', 'Apple'],
      order: 13,
    },
    {
      slug: 'aggressive-cows',
      title: 'Magnetic Force Between Two Balls',
      difficulty: 'medium',
      tags: ['binary-search', 'array', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/magnetic-force-between-two-balls/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=magnetic+force+between+two+balls',
      articleUrl: 'https://www.geeksforgeeks.org/aggressive-cows/',
      companies: ['Google', 'Amazon'],
      order: 14,
    },
    {
      slug: 'book-allocation',
      title: 'Allocate Minimum Pages',
      difficulty: 'medium',
      tags: ['binary-search', 'array', 'greedy'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/split-array-largest-sum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=book+allocation+problem',
      articleUrl: 'https://www.geeksforgeeks.org/allocate-minimum-number-pages/',
      companies: ['Google', 'Amazon', 'Microsoft'],
      order: 15,
    },
  ],

  greedy: [
    {
      slug: 'assign-cookies',
      title: 'Assign Cookies',
      difficulty: 'easy',
      tags: ['greedy', 'array', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/assign-cookies/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=assign+cookies+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/assign-cookies/',
      companies: ['Amazon'],
      order: 1,
    },
    {
      slug: 'lemonade-change',
      title: 'Lemonade Change',
      difficulty: 'easy',
      tags: ['greedy', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/lemonade-change/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=lemonade+change+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/lemonade-change-problem/',
      companies: ['Amazon', 'Google'],
      order: 2,
    },
    {
      slug: 'jump-game',
      title: 'Jump Game',
      difficulty: 'medium',
      tags: ['greedy', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/jump-game/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=jump+game',
      articleUrl:
        'https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/',
      companies: ['Amazon', 'Microsoft'],
      order: 3,
    },
    {
      slug: 'jump-game-ii',
      title: 'Jump Game II',
      difficulty: 'medium',
      tags: ['greedy', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/jump-game-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=jump+game+ii',
      articleUrl:
        'https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/',
      companies: ['Amazon', 'Google'],
      order: 4,
    },
    {
      slug: 'gas-station',
      title: 'Gas Station',
      difficulty: 'medium',
      tags: ['greedy', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/gas-station/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=gas+station',
      articleUrl: 'https://www.geeksforgeeks.org/find-a-tour-that-visits-all-stations/',
      companies: ['Amazon', 'Bloomberg'],
      order: 5,
    },
    {
      slug: 'task-scheduler',
      title: 'Task Scheduler',
      difficulty: 'medium',
      tags: ['greedy', 'hash-table', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/task-scheduler/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=task+scheduler',
      articleUrl: 'https://www.geeksforgeeks.org/task-scheduler/',
      companies: ['Meta', 'Amazon', 'Google'],
      order: 6,
    },
    {
      slug: 'non-overlapping-intervals',
      title: 'Non-overlapping Intervals',
      difficulty: 'medium',
      tags: ['greedy', 'array', 'sorting', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/non-overlapping-intervals/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=non+overlapping+intervals',
      articleUrl:
        'https://www.geeksforgeeks.org/minimum-number-of-intervals-to-remove-to-make-non-overlapping/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 7,
    },
    {
      slug: 'merge-intervals-greedy',
      title: 'Merge Intervals',
      difficulty: 'medium',
      tags: ['greedy', 'array', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/merge-intervals/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=merge+intervals+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/merging-intervals/',
      companies: ['Google', 'Meta', 'Bloomberg'],
      order: 8,
    },
    {
      slug: 'minimum-number-of-platforms',
      title: 'Meeting Rooms II',
      difficulty: 'medium',
      tags: ['greedy', 'array', 'sorting', 'heap'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/meeting-rooms-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=meeting+rooms+ii',
      articleUrl:
        'https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 9,
    },
    {
      slug: 'minimum-number-of-arrows-to-burst-balloons',
      title: 'Minimum Number of Arrows to Burst Balloons',
      difficulty: 'medium',
      tags: ['greedy', 'array', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=minimum+arrows+burst+balloons',
      articleUrl: 'https://www.geeksforgeeks.org/minimum-number-of-arrows-to-burst-balloons/',
      companies: ['Meta', 'Amazon'],
      order: 10,
    },
    {
      slug: 'hand-of-straights',
      title: 'Hand of Straights',
      difficulty: 'medium',
      tags: ['greedy', 'array', 'hash-table', 'sorting'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/hand-of-straights/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=hand+of+straights+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/hand-of-straights/',
      companies: ['Google', 'Amazon'],
      order: 11,
    },
    {
      slug: 'partition-labels',
      title: 'Partition Labels',
      difficulty: 'medium',
      tags: ['greedy', 'hash-table', 'two-pointers', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/partition-labels/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=partition+labels+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/partition-labels/',
      companies: ['Amazon', 'Google'],
      order: 12,
    },
    {
      slug: 'valid-parenthesis-string',
      title: 'Valid Parenthesis String',
      difficulty: 'medium',
      tags: ['greedy', 'string', 'dynamic-programming', 'stack'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/valid-parenthesis-string/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=valid+parenthesis+string',
      articleUrl:
        'https://www.geeksforgeeks.org/check-if-the-bracket-sequence-can-be-balanced-with-at-most-one-change-in-the-position-of-a-bracket/',
      companies: ['Amazon', 'Meta'],
      order: 13,
    },
    {
      slug: 'candy',
      title: 'Candy',
      difficulty: 'hard',
      tags: ['greedy', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/candy/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=candy+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/minimum-number-of-candies-required-to-distribute-among-children-based-on-given-conditions/',
      companies: ['Amazon', 'Google', 'Bloomberg'],
      order: 14,
    },
    {
      slug: 'insert-interval',
      title: 'Insert Interval',
      difficulty: 'medium',
      tags: ['greedy', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/insert-interval/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=insert+interval+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/insert-in-sorted-and-non-overlapping-interval-array/',
      companies: ['Google', 'Meta', 'Amazon'],
      order: 15,
    },
  ],

  backtracking: [
    {
      slug: 'subsets',
      title: 'Subsets',
      difficulty: 'medium',
      tags: ['backtracking', 'array', 'bit-manipulation'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/subsets/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=subsets+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/backtracking-to-find-all-subsets/',
      companies: ['Amazon', 'Meta', 'Google'],
      order: 1,
    },
    {
      slug: 'subsets-ii',
      title: 'Subsets II',
      difficulty: 'medium',
      tags: ['backtracking', 'array', 'bit-manipulation'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/subsets-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=subsets+ii+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/find-distinct-subsets-given-set/',
      companies: ['Amazon', 'Meta'],
      order: 2,
    },
    {
      slug: 'combination-sum',
      title: 'Combination Sum',
      difficulty: 'medium',
      tags: ['backtracking', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/combination-sum/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=combination+sum',
      articleUrl: 'https://www.geeksforgeeks.org/combinational-sum/',
      companies: ['Amazon', 'Apple'],
      order: 3,
    },
    {
      slug: 'combination-sum-ii',
      title: 'Combination Sum II',
      difficulty: 'medium',
      tags: ['backtracking', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/combination-sum-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=combination+sum+ii',
      articleUrl: 'https://www.geeksforgeeks.org/combination-sum-ii/',
      companies: ['Amazon', 'Google'],
      order: 4,
    },
    {
      slug: 'permutations',
      title: 'Permutations',
      difficulty: 'medium',
      tags: ['backtracking', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/permutations/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=permutations+leetcode',
      articleUrl:
        'https://www.geeksforgeeks.org/write-a-c-program-to-print-all-permutations-of-a-given-string/',
      companies: ['Amazon', 'Meta', 'Microsoft'],
      order: 5,
    },
    {
      slug: 'permutations-ii',
      title: 'Permutations II',
      difficulty: 'medium',
      tags: ['backtracking', 'array'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/permutations-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=permutations+ii+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/distinct-permutations-string-set-2/',
      companies: ['Amazon', 'Meta'],
      order: 6,
    },
    {
      slug: 'word-search',
      title: 'Word Search',
      difficulty: 'medium',
      tags: ['backtracking', 'matrix'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/word-search/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=word+search+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/search-a-word-in-a-2d-grid-of-characters/',
      companies: ['Amazon', 'Microsoft', 'Bloomberg'],
      order: 7,
    },
    {
      slug: 'palindrome-partitioning',
      title: 'Palindrome Partitioning',
      difficulty: 'medium',
      tags: ['backtracking', 'string', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/palindrome-partitioning/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=palindrome+partitioning',
      articleUrl:
        'https://www.geeksforgeeks.org/given-a-string-print-all-possible-palindromic-partition/',
      companies: ['Amazon', 'Google'],
      order: 8,
    },
    {
      slug: 'letter-combinations-of-a-phone-number',
      title: 'Letter Combinations of a Phone Number',
      difficulty: 'medium',
      tags: ['backtracking', 'string', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=letter+combinations+phone+number',
      articleUrl: 'https://www.geeksforgeeks.org/iterative-letter-combinations-of-a-phone-number/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 9,
    },
    {
      slug: 'generate-parentheses',
      title: 'Generate Parentheses',
      difficulty: 'medium',
      tags: ['backtracking', 'string', 'dynamic-programming'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/generate-parentheses/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=generate+parentheses',
      articleUrl: 'https://www.geeksforgeeks.org/print-all-combinations-of-balanced-parentheses/',
      companies: ['Amazon', 'Google', 'Meta'],
      order: 10,
    },
    {
      slug: 'rat-in-a-maze',
      title: 'Unique Paths III',
      difficulty: 'hard',
      tags: ['backtracking', 'matrix', 'bit-manipulation'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/unique-paths-iii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=unique+paths+iii',
      articleUrl: 'https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-2/',
      companies: ['Google', 'Amazon'],
      order: 11,
    },
    {
      slug: 'sudoku-solver',
      title: 'Sudoku Solver',
      difficulty: 'hard',
      tags: ['backtracking', 'matrix', 'hash-table'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/sudoku-solver/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=sudoku+solver+leetcode',
      articleUrl: 'https://www.geeksforgeeks.org/sudoku-backtracking-7/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 12,
    },
    {
      slug: 'n-queens',
      title: 'N-Queens',
      difficulty: 'hard',
      tags: ['backtracking'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/n-queens/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=n+queens',
      articleUrl: 'https://www.geeksforgeeks.org/n-queen-problem-backtracking-3/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 13,
    },
    {
      slug: 'word-search-ii',
      title: 'Word Search II',
      difficulty: 'hard',
      tags: ['backtracking', 'trie', 'matrix'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/word-search-ii/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=word+search+ii',
      articleUrl: 'https://www.geeksforgeeks.org/boggle-find-possible-words-board-characters/',
      companies: ['Amazon', 'Google', 'Microsoft'],
      order: 14,
    },
    {
      slug: 'expression-add-operators',
      title: 'Expression Add Operators',
      difficulty: 'hard',
      tags: ['backtracking', 'math', 'string'],
      platform: 'leetcode',
      problemUrl: 'https://leetcode.com/problems/expression-add-operators/',
      youtubeUrl: 'https://www.youtube.com/results?search_query=expression+add+operators',
      articleUrl: 'https://www.geeksforgeeks.org/expression-contains-redundant-bracket-not/',
      companies: ['Meta', 'Google', 'Amazon'],
      order: 15,
    },
  ],
};

/**
 * Seeds the database with topics and problems.
 * Drops existing data, inserts topics, inserts problems, and updates topic counts.
 */
async function seed(): Promise<void> {
  try {
    logger.info('Connecting to MongoDB...');
    await mongoose.connect(env.MONGODB_URI);
    logger.info('Connected to MongoDB');

    // Drop existing collections
    logger.info('Dropping existing topics and problems collections...');
    await Topic.deleteMany({});
    await Problem.deleteMany({});
    logger.info('Existing data dropped');

    // Insert topics
    const insertedTopics = await Topic.insertMany(topicsSeed);
    logger.info(`Inserted ${insertedTopics.length} topics`);

    // Build a slug-to-ID map
    const topicSlugToId = new Map<string, mongoose.Types.ObjectId>();
    for (const topic of insertedTopics) {
      topicSlugToId.set(topic.slug, topic._id as mongoose.Types.ObjectId);
    }

    // Insert problems for each topic
    let totalProblems = 0;
    for (const [topicSlug, problems] of Object.entries(problemsSeed)) {
      const topicId = topicSlugToId.get(topicSlug);
      if (!topicId) {
        logger.warn(`Topic slug '${topicSlug}' not found, skipping its problems`);
        continue;
      }

      const problemDocs = problems.map((problem) => ({
        ...problem,
        topicId,
      }));

      await Problem.insertMany(problemDocs);
      totalProblems += problemDocs.length;

      // Update the topic's totalProblems count
      await Topic.findByIdAndUpdate(topicId, { totalProblems: problemDocs.length });
    }

    logger.info(`Seeded ${insertedTopics.length} topics and ${totalProblems} problems`);
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    logger.error('Seed script failed', { error: message });
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    logger.info('Disconnected from MongoDB');
  }
}

seed();
