FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@9.12.0 --activate
RUN npm install -g nodemon

WORKDIR /app

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY apps/api/package.json apps/api/

RUN pnpm install --filter @dsa-tracker/api

COPY apps/api/ apps/api/

EXPOSE 5000

WORKDIR /app/apps/api

CMD ["pnpm", "dev"]
